[project]
name = "phone-num-extraction"
version = "0.1.0"
description = "A simple script to extract phone numbers from text data"
authors = [
  { name = "Your Name", email = "your_email@example.com" }
]
requires-python = ">3.12"
dependencies = [
    "pandas",
]
